// <auto-generated />
namespace MyELearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_service_contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_service_contact));
        
        string IMigrationMetadata.Id
        {
            get { return "202309172122435_mig_service_contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
