// <auto-generated />
namespace MyELearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_review_virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_review_virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "202311222036312_mig_review_virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
